# Generated by Django 5.0.6 on 2024-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date published')),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('choice_text', models.CharField(max_length=100)),
            ],
        ),
    ]
