# Generated by Django 5.0.6 on 2024-05-20 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_password_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
