# Generated by Django 5.0.6 on 2024-05-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0003_password_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='username',
            field=models.CharField(default='user123', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='password',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
