# Generated by Django 5.0.6 on 2024-06-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0004_passwordentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordEntry',
        ),
    ]
